"""schema initial

Revision ID: 7608d703d502
Revises: 
Create Date: 2026-08-10 19:01:00.769840
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7608d703d502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    op.execute("CREATE SCHEMA IF NOT EXISTS market")
    op.execute("CREATE SCHEMA IF NOT EXISTS household")
    op.execute("CREATE SCHEMA IF NOT EXISTS staging")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_ingredient',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_kind', sa.Enum('mass', 'volume', 'count', name='unit_kind', schema='catalog'), nullable=False),
    sa.Column('base_unit', sa.String(length=8), nullable=False),
    sa.Column('perishability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('salvage_value_cents_per_base_unit', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('density_g_per_ml', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('density_g_per_ml IS NULL OR density_g_per_ml > 0', name=op.f('ck_canonical_ingredient_density_positive')),
    sa.CheckConstraint('perishability >= 0 AND perishability <= 1', name=op.f('ck_canonical_ingredient_perishability_01')),
    sa.CheckConstraint('salvage_value_cents_per_base_unit >= 0', name=op.f('ck_canonical_ingredient_salvage_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_ingredient')),
    schema='catalog'
    )
    op.create_table('recipe',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('original_servings', sa.Integer(), nullable=False),
    sa.Column('prep_time_fixed_h', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('prep_time_marginal_h', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('min_batch_servings', sa.Integer(), nullable=False),
    sa.Column('max_batch_servings', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diet_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergen_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_batch_servings >= min_batch_servings', name=op.f('ck_recipe_m_ge_beta')),
    sa.CheckConstraint('min_batch_servings >= 1', name=op.f('ck_recipe_beta_ge_1')),
    sa.CheckConstraint('original_servings >= 1', name=op.f('ck_recipe_pi_ge_1')),
    sa.CheckConstraint('prep_time_fixed_h >= 0 AND prep_time_marginal_h >= 0', name=op.f('ck_recipe_prep_time_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe')),
    schema='catalog'
    )
    op.create_table('household_profile',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('home_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('home_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('time_value_cents_per_hour', sa.Integer(), nullable=False),
    sa.Column('meals_per_horizon', sa.Integer(), nullable=False),
    sa.Column('demand_slack_epsilon', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('max_store_visits', sa.Integer(), nullable=False),
    sa.Column('min_distinct_recipes', sa.Integer(), nullable=False),
    sa.Column('max_share_per_recipe', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('diet_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergen_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('taste_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_prep_time_per_meal_h', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('demand_slack_epsilon >= 0 AND demand_slack_epsilon < 1', name=op.f('ck_household_profile_epsilon_range')),
    sa.CheckConstraint('max_share_per_recipe > 0 AND max_share_per_recipe <= 1', name=op.f('ck_household_profile_alpha_01')),
    sa.CheckConstraint('max_store_visits >= 1', name=op.f('ck_household_profile_k_ge_1')),
    sa.CheckConstraint('meals_per_horizon > 0', name=op.f('ck_household_profile_meals_positive')),
    sa.CheckConstraint('min_distinct_recipes >= 1', name=op.f('ck_household_profile_rmin_ge_1')),
    sa.CheckConstraint('time_value_cents_per_hour >= 0', name=op.f('ck_household_profile_kappa_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_profile')),
    schema='household'
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_key', sa.String(length=64), nullable=False),
    sa.Column('banner', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('shopping_center_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store')),
    sa.UniqueConstraint('external_key', name=op.f('uq_store_external_key')),
    schema='market'
    )
    op.create_table('raw_offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_external_key', sa.String(length=64), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('mapping_status', sa.Enum('unmapped', 'auto', 'confirmed', 'rejected', name='mapping_status', schema='staging'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_offer')),
    sa.UniqueConstraint('store_external_key', 'week', 'payload_fingerprint', name=op.f('uq_raw_offer_store_external_key_week_payload_fingerprint')),
    schema='staging'
    )
    op.create_index('ix_raw_offer_status', 'raw_offer', ['mapping_status'], unique=False, schema='staging')
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('qty_fixed_per_batch_base_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_marginal_per_serving_base_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('substitutable', sa.Boolean(), nullable=False),
    sa.CheckConstraint('qty_fixed_per_batch_base_unit >= 0 AND qty_marginal_per_serving_base_unit >= 0', name=op.f('ck_recipe_ingredient_qty_nonneg')),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['catalog.canonical_ingredient.id'], name=op.f('fk_recipe_ingredient_canonical_ingredient_id_canonical_ingredient')),
    sa.ForeignKeyConstraint(['recipe_id'], ['catalog.recipe.id'], name=op.f('fk_recipe_ingredient_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredient')),
    sa.UniqueConstraint('recipe_id', 'canonical_ingredient_id', name=op.f('uq_recipe_ingredient_recipe_id_canonical_ingredient_id')),
    schema='catalog'
    )
    op.create_table('household_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_profile_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('appetite_coefficient', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('appetite_coefficient > 0', name=op.f('ck_household_member_rho_positive')),
    sa.ForeignKeyConstraint(['household_profile_id'], ['household.household_profile.id'], name=op.f('fk_household_member_household_profile_id_household_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_member')),
    sa.UniqueConstraint('household_profile_id', 'name', name=op.f('uq_household_member_household_profile_id_name')),
    schema='household'
    )
    op.create_table('pantry_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_profile_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_base_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity_base_unit >= 0', name=op.f('ck_pantry_stock_qty_nonneg')),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['catalog.canonical_ingredient.id'], name=op.f('fk_pantry_stock_canonical_ingredient_id_canonical_ingredient')),
    sa.ForeignKeyConstraint(['household_profile_id'], ['household.household_profile.id'], name=op.f('fk_pantry_stock_household_profile_id_household_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_stock')),
    sa.UniqueConstraint('household_profile_id', 'canonical_ingredient_id', name=op.f('uq_pantry_stock_household_profile_id_canonical_ingredient_id')),
    schema='household'
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_profile_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'committed', name='plan_status', schema='household'), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('solver_status', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('servings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('purchases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingredient_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stores_visited', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['household_profile_id'], ['household.household_profile.id'], name=op.f('fk_plan_household_profile_id_household_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    schema='household'
    )
    op.create_index('ix_plan_profile_status', 'plan', ['household_profile_id', 'status'], unique=False, schema='household')
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_key', sa.String(length=64), nullable=False),
    sa.Column('canonical_ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('package_qty_in_base_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('package_unit', sa.String(length=32), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('package_qty_in_base_unit > 0', name=op.f('ck_product_package_qty_positive')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate < 1', name=op.f('ck_product_tax_rate_range')),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['catalog.canonical_ingredient.id'], name=op.f('fk_product_canonical_ingredient_id_canonical_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('external_key', name=op.f('uq_product_external_key')),
    schema='market'
    )
    op.create_table('product_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.String(length=255), nullable=False),
    sa.Column('canonical_ingredient_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confirmed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_product_mapping_confidence_01')),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['catalog.canonical_ingredient.id'], name=op.f('fk_product_mapping_canonical_ingredient_id_canonical_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_mapping')),
    sa.UniqueConstraint('raw_text', name=op.f('uq_product_mapping_raw_text')),
    schema='market'
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price_cents_cad', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('regular_price_cents_cad', sa.Integer(), nullable=True),
    sa.CheckConstraint('price_cents_cad >= 0', name=op.f('ck_price_price_nonneg')),
    sa.CheckConstraint('regular_price_cents_cad IS NULL OR regular_price_cents_cad >= 0', name=op.f('ck_price_regular_price_nonneg')),
    sa.CheckConstraint('valid_to >= valid_from', name=op.f('ck_price_validity_ordered')),
    sa.ForeignKeyConstraint(['product_id'], ['market.product.id'], name=op.f('fk_price_product_id_product')),
    sa.ForeignKeyConstraint(['store_id'], ['market.store.id'], name=op.f('fk_price_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price')),
    sa.UniqueConstraint('product_id', 'store_id', 'valid_from', name=op.f('uq_price_product_id_store_id_valid_from')),
    schema='market'
    )
    op.create_index('ix_price_validity', 'price', ['store_id', 'valid_from', 'valid_to'], unique=False, schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_validity', table_name='price', schema='market')
    op.drop_table('price', schema='market')
    op.drop_table('product_mapping', schema='market')
    op.drop_table('product', schema='market')
    op.drop_index('ix_plan_profile_status', table_name='plan', schema='household')
    op.drop_table('plan', schema='household')
    op.drop_table('pantry_stock', schema='household')
    op.drop_table('household_member', schema='household')
    op.drop_table('recipe_ingredient', schema='catalog')
    op.drop_index('ix_raw_offer_status', table_name='raw_offer', schema='staging')
    op.drop_table('raw_offer', schema='staging')
    op.drop_table('store', schema='market')
    op.drop_table('household_profile', schema='household')
    op.drop_table('recipe', schema='catalog')
    op.drop_table('canonical_ingredient', schema='catalog')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS staging CASCADE")
    op.execute("DROP SCHEMA IF EXISTS household CASCADE")
    op.execute("DROP SCHEMA IF EXISTS market CASCADE")
    op.execute("DROP SCHEMA IF EXISTS catalog CASCADE")
